// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEJlHp8cTDerWdgdAhhmhyNBiKjYIPFyM',
    appId: '1:457312688533:web:18fd636afd8176538d7e9c',
    messagingSenderId: '457312688533',
    projectId: 'fir-flutter-d1c6f',
    authDomain: 'fir-flutter-d1c6f.firebaseapp.com',
    storageBucket: 'fir-flutter-d1c6f.firebasestorage.app',
    measurementId: 'G-758C196Z44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMXSsMsRHNJBhoU4nxiiPKU399Ouc7x0M',
    appId: '1:457312688533:android:e54e8deabd30c4268d7e9c',
    messagingSenderId: '457312688533',
    projectId: 'fir-flutter-d1c6f',
    storageBucket: 'fir-flutter-d1c6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj4hpH3hCQ1gSAwP2ybyuIDqu9DXn5J6I',
    appId: '1:457312688533:ios:c5f380ad5aee8d538d7e9c',
    messagingSenderId: '457312688533',
    projectId: 'fir-flutter-d1c6f',
    storageBucket: 'fir-flutter-d1c6f.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj4hpH3hCQ1gSAwP2ybyuIDqu9DXn5J6I',
    appId: '1:457312688533:ios:c5f380ad5aee8d538d7e9c',
    messagingSenderId: '457312688533',
    projectId: 'fir-flutter-d1c6f',
    storageBucket: 'fir-flutter-d1c6f.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEJlHp8cTDerWdgdAhhmhyNBiKjYIPFyM',
    appId: '1:457312688533:web:18a7d452b09d08558d7e9c',
    messagingSenderId: '457312688533',
    projectId: 'fir-flutter-d1c6f',
    authDomain: 'fir-flutter-d1c6f.firebaseapp.com',
    storageBucket: 'fir-flutter-d1c6f.firebasestorage.app',
    measurementId: 'G-4BV960KNVK',
  );
}
